Revert "Update README.md"
plaid/plaid-postman pull request #161
Opened 2024-04-19 09:08 UTC by bobbid381

Reverts plaid/plaid-postman#157

2024-04-19 09:58 UTC, romeroj748 approved these changes
[](url)

2024-04-19 10:02 UTC, romeroj748 requested changes

2024-04-19 10:02 UTC, romeroj748 commented on README.md
>  Don't feel like reading? Check out our [Plaid and Postman in Three Minutes Quickstart video](https://www.youtube.com/watch?v=f4NhgHpp5aA). Or, for a more detailed walkthrough, watch the [Plaid Postma
[]()

2024-04-21 02:45 UTC, Slsadler14 approved these changes

2024-04-23 07:41 UTC, romeroj748 approved these changes

2024-04-24 11:39 UTC, romeroj748 approved these changes

2024-07-24 04:55 UTC, closed without merging